/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

public class TalairachLabels {

    public String getLabel( int index) { return label[index]; };	
    public int getCount() { return label.length; };

    // here follows 1105 talairach label descriptors - no code beyond this 
    // label[0] is undefined
	public String[] label = {  
			"*", 
			 "Left Cerebellum Posterior Lobe Inferior Semi-Lunar Lobule Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Inferior Semi-Lunar Lobule Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Cerebellar Tonsil Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Cerebellar Tonsil Gray Matter" ,
			 "Left Brainstem Medulla" ,
			 "Right Brainstem Medulla" ,
			 "Inferior Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe" ,
			 "Right Cerebrum Temporal Lobe" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Limbic Lobe Uncus" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Limbic Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe" ,
			 "Right Cerebrum Limbic Lobe" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Uncus White Matter" ,
			 "Right Cerebrum Limbic Lobe Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Limbic Lobe Uncus White Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Uncus" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Limbic Lobe Middle Temporal Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus" ,
			 "Right Cerebrum Temporal Lobe Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Temporal Lobe Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Frontal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Inferior Temporal Gyrus" ,
			 "Right Cerebrum" ,
			 "Left Cerebrum Limbic Lobe Inferior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Inferior Temporal Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral White Matter" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral White Matter" ,
			 "Left Cerebrum Limbic Lobe Gray Matter Brodmann area 20" ,
			 "Middle Temporal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral White Matter" ,
			 "Left Cerebrum Limbic Lobe Superior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Superior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Uncus" ,
			 "Left Cerebrum Limbic Lobe Superior Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Limbic Lobe Superior Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Left Cerebellum Posterior Lobe Pyramis Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Pyramis Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Uvula Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Uvula Gray Matter" ,
			 "Right Cerebellum Gray Matter" ,
			 "Left Cerebellum Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Uvula of Vermis Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Uvula of Vermis Gray Matter" ,
			 "Right Cerebellum Sub-lobar Fourth Ventricle Cerebro-Spinal Fluid" ,
			 "Left Cerebellum Sub-lobar Fourth Ventricle Cerebro-Spinal Fluid" ,
			 "Left Brainstem Pons" ,
			 "Right Brainstem Pons" ,
			 "Limbic Lobe Uncus" ,
			 "Left Cerebrum" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 36" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 36" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Left Cerebellum Posterior Lobe Tuber Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Tuber Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Pyramis of Vermis Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Pyramis of Vermis Gray Matter" ,
			 "Left Cerebellum Anterior Lobe Nodule Gray Matter" ,
			 "Left Cerebellum Anterior Lobe Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Nodule Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Gray Matter" ,
			 "Left Cerebellum Anterior Lobe Culmen Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Culmen Gray Matter" ,
			 "Temporal Lobe" ,
			 "Temporal Lobe Inferior Temporal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Inferior Temporal Gyrus" ,
			 "Left Cerebrum Limbic Lobe Inferior Temporal Gyrus" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 28" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 28" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral White Matter" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Left Cerebrum Inferior Temporal Gyrus" ,
			 "Left Cerebrum Middle Temporal Gyrus" ,
			 "Left Cerebrum Superior Temporal Gyrus" ,
			 "Left Cerebrum Superior Temporal Gyrus Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Frontal Lobe Orbital Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Orbital Gyrus Gray Matter Brodmann area 11" ,
			 "Frontal Lobe Orbital Gyrus" ,
			 "Left Cerebrum Frontal Lobe Orbital Gyrus" ,
			 "Left Cerebrum Frontal Lobe" ,
			 "Inter-Hemispheric" ,
			 "Right Cerebrum Frontal Lobe" ,
			 "Right Cerebrum Frontal Lobe Orbital Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Orbital Gyrus" ,
			 "Orbital Gyrus" ,
			 "Left Cerebrum Frontal Lobe Orbital Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Orbital Gyrus White Matter" ,
			 "Left Cerebellum Posterior Lobe Tuber of Vermis Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Tuber of Vermis Gray Matter" ,
			 "Left Cerebellum Anterior Lobe Pyramis Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Pyramis Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Gray Matter Dentate" ,
			 "Left Cerebellum Anterior Lobe Gray Matter Dentate" ,
			 "Left Cerebellum Posterior Lobe Culmen Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus" ,
			 "Limbic Lobe Parahippocampal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 36" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 36" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Fusiform Gyrus" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Fusiform Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 36" ,
			 "Left Cerebrum Limbic Lobe Fusiform Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Fusiform Gyrus White Matter" ,
			 "Fusiform Gyrus" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 35" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 35" ,
			 "Left Cerebrum Frontal Lobe Rectal Gyrus Gray Matter Brodmann area 11" ,
			 "Left Cerebrum Frontal Lobe Rectal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Rectal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Rectal Gyrus Gray Matter Brodmann area 11" ,
			 "Left Cerebrum Frontal Lobe Orbital Gyrus Gray Matter Brodmann area 47" ,
			 "Right Cerebrum Frontal Lobe Orbital Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Rectal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Rectal Gyrus White Matter" ,
			 "Inter-Hemispheric Rectal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus White Matter" ,
			 "Left Cerebellum Posterior Lobe Declive Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Declive Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Declive of Vermis Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Declive of Vermis Gray Matter" ,
			 "Left Cerebellum Posterior Lobe Gray Matter Dentate" ,
			 "Left Cerebellum Posterior Lobe Fastigium Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Fastigium Gray Matter" ,
			 "Right Cerebellum Posterior Lobe Gray Matter Dentate" ,
			 "Left Cerebellum Anterior Lobe Fastigium Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 36" ,
			 "Right Cerebrum Fusiform Gyrus Gray Matter Brodmann area 20" ,
			 "Temporal Lobe Fusiform Gyrus" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 28" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 28" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Sub-lobar Lateral Ventricle Cerebro-Spinal Fluid" ,
			 "Right Cerebrum Sub-lobar Lateral Ventricle Cerebro-Spinal Fluid" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Hippocampus" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Hippocampus" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 34" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 34" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Limbic Lobe Uncus Gray Matter Amygdala" ,
			 "Right Cerebrum Limbic Lobe Uncus Gray Matter Amygdala" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Amygdala" ,
			 "Inferior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral White Matter" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral White Matter" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus" ,
			 "Right Cerebrum Orbital Gyrus" ,
			 "Right Cerebrum Superior Frontal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Fusiform Gyrus" ,
			 "Left Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Fusiform Gyrus" ,
			 "Right Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Fusiform Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Fusiform Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Fusiform Gyrus" ,
			 "Left Cerebellum Anterior Lobe Cerebellar Lingual Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Cerebellar Lingual Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Left Brainstem Midbrain" ,
			 "Right Brainstem Midbrain" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 20" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 20" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Amygdala" ,
			 "White Matter" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 38" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 38" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Superior Temporal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Frontal Lobe Superior Temporal Gyrus" ,
			 "Right Cerebrum Temporal Lobe Inferior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Inferior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 25" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 25" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus" ,
			 "Lingual Gyrus" ,
			 "Occipital Lobe" ,
			 "Occipital Lobe Lingual Gyrus" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 17" ,
			 "Inter-Hemispheric Occipital Lobe Lingual Gyrus" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 17" ,
			 "Left Cerebrum Occipital Lobe" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Inferior Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Inferior Occipital Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Inferior Occipital Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Inferior Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 19" ,
			 "Inferior Occipital Gyrus" ,
			 "Left Cerebrum Inferior Occipital Gyrus" ,
			 "Right Cerebrum Inferior Occipital Gyrus" ,
			 "Right Cerebrum Occipital Lobe Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Occipital Lobe Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Temporal Lobe Fusiform Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Temporal Lobe Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Temporal Lobe Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Limbic Lobe Gray Matter Brodmann area 35" ,
			 "White Matter Optic Tract" ,
			 "Gray Matter Hypothalamus" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 21" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus" ,
			 "Left Cerebrum Limbic Lobe Subcallosal Gyrus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 34" ,
			 "Right Cerebrum Limbic Lobe Subcallosal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Subcallosal Gyrus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 21" ,
			 "Left Cerebrum Temporal Lobe Subcallosal Gyrus Gray Matter Brodmann area 34" ,
			 "Left Cerebrum Temporal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Temporal Lobe Inferior Frontal Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Temporal Lobe Inferior Frontal Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 47" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Subcallosal Gyrus Gray Matter Brodmann area 11" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 17" ,
			 "Right Cerebrum Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 17" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus White Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Sub-Gyral" ,
			 "Right Cerebrum Sub-Gyral" ,
			 "Right Cerebrum Occipital Lobe Sub-Gyral" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Middle Occipital Gyrus" ,
			 "Right Cerebrum Lingual Gyrus" ,
			 "Left Cerebrum Occipital Lobe Sub-Gyral White Matter" ,
			 "Right Cerebrum Occipital Lobe Sub-Gyral White Matter" ,
			 "Left Cerebellum Anterior Lobe Culmen of Vermis Gray Matter" ,
			 "Right Cerebellum Anterior Lobe Culmen of Vermis Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Fusiform Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Parahippocampal Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Limbic Lobe Fusiform Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Hippocampus" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Hippocampus" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Hippocampus" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Hippocampus" ,
			 "Left Brainstem Midbrain Gray Matter Substania Nigra" ,
			 "Right Brainstem Midbrain Gray Matter Substania Nigra" ,
			 "Left Brainstem Midbrain Gray Matter Red Nucleus" ,
			 "Right Brainstem Midbrain Gray Matter Red Nucleus" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 28" ,
			 "Right Cerebrum Limbic Lobe White Matter" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter" ,
			 "Left Cerebrum Temporal Lobe Gray Matter Caudate Tail" ,
			 "Right Cerebrum Temporal Lobe Caudate Gray Matter Caudate Tail" ,
			 "Left Cerebrum Temporal Lobe Caudate Gray Matter Caudate Tail" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 21" ,
			 "Left Cerebrum Temporal Lobe Extra-Nuclear White Matter" ,
			 "Left Brainstem Midbrain Gray Matter Mammillary Body" ,
			 "Right Brainstem Midbrain Gray Matter Mammillary Body" ,
			 "Left Cerebrum Sub-lobar Gray Matter Amygdala" ,
			 "Right Cerebrum White Matter" ,
			 "Right Cerebrum Sub-lobar Gray Matter Amygdala" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Optic Tract" ,
			 "Right Cerebrum Sub-lobar Third Ventricle Cerebro-Spinal Fluid" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Optic Tract" ,
			 "Left Cerebrum Sub-lobar Third Ventricle Cerebro-Spinal Fluid" ,
			 "Left Cerebrum Sub-lobar Gray Matter Hypothalamus" ,
			 "Right Cerebrum Sub-lobar Gray Matter Hypothalamus" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Limbic Lobe Extra-Nuclear White Matter" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate White Matter" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate White Matter" ,
			 "Right Cerebrum Limbic Lobe Extra-Nuclear White Matter" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear" ,
			 "Left Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Putamen" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 25" ,
			 "Right Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Putamen" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral" ,
			 "Left Cerebrum Sub-lobar Gray Matter" ,
			 "Right Cerebrum Sub-lobar Gray Matter" ,
			 "Temporal Lobe Superior Temporal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral" ,
			 "Left Cerebrum Frontal Lobe Extra-Nuclear" ,
			 "Right Cerebrum Frontal Lobe Extra-Nuclear" ,
			 "Left Cerebrum Frontal Lobe Extra-Nuclear Gray Matter Brodmann area 47" ,
			 "Right Cerebrum Frontal Lobe Extra-Nuclear Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal-Temporal Space" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Frontal-Temporal Space" ,
			 "Left Cerebrum Frontal-Temporal Space Inferior Frontal Gyrus" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Extra-Nuclear Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear Gray Matter Brodmann area 47" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Extra-Nuclear White Matter" ,
			 "Right Cerebrum Frontal Lobe Extra-Nuclear White Matter" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Inferior Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Sub-Gyral" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Limbic Lobe Lingual Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 30" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 30" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 30" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 27" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 27" ,
			 "Right Cerebrum Temporal Lobe White Matter" ,
			 "Left Cerebrum Sub-lobar Caudate Gray Matter Caudate Tail" ,
			 "Right Cerebrum Sub-lobar Caudate Gray Matter Caudate Tail" ,
			 "Left Brainstem Midbrain Thalamus Gray Matter Medial Geniculum Body" ,
			 "Right Brainstem Midbrain Thalamus Gray Matter Medial Geniculum Body" ,
			 "Left Cerebrum Sub-lobar Insula White Matter" ,
			 "Right Cerebrum Midbrain" ,
			 "Right Cerebrum Sub-lobar Insula White Matter" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 22" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 22" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Sub-lobar Insula" ,
			 "Left Cerebrum Sub-lobar Claustrum Gray Matter" ,
			 "Right Cerebrum Sub-lobar Claustrum Gray Matter" ,
			 "Right Cerebrum Sub-lobar Insula" ,
			 "Left Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Lateral Globus Pallidus" ,
			 "Left Brainstem Midbrain Gray Matter Subthalamic Nucleus" ,
			 "Right Brainstem Midbrain Gray Matter Subthalamic Nucleus" ,
			 "Right Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Lateral Globus Pallidus" ,
			 "Left Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Medial Globus Pallidus" ,
			 "Right Cerebrum Sub-lobar Lentiform Nucleus Gray Matter Medial Globus Pallidus" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Right Brainstem Midbrain Extra-Nuclear White Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Sub-lobar White Matter" ,
			 "Right Cerebrum Sub-lobar White Matter" ,
			 "Right Cerebrum Temporal Lobe Insula" ,
			 "Left Cerebrum Sub-lobar Caudate Gray Matter Caudate Head" ,
			 "Right Cerebrum Sub-lobar Caudate Gray Matter Caudate Head" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 47" ,
			 "Right Cerebrum Sub-lobar Inferior Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 24" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 24" ,
			 "Right Cerebrum Frontal Lobe Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Medial Frontal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Cuneus" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 17" ,
			 "Right Cerebrum Occipital Lobe Cuneus" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 17" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 30" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus Gray Matter Brodmann area 30" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Occipital Lobe Cuneus White Matter" ,
			 "Right Cerebrum Occipital Lobe Cuneus White Matter" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Limbic Lobe Lingual Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter" ,
			 "Left Cerebrum Temporal Lobe White Matter Caudate Tail" ,
			 "Left Cerebrum Sub-lobar Caudate Gray Matter" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Caudate Tail" ,
			 "Right Cerebrum Sub-lobar Caudate Gray Matter" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Caudate Tail" ,
			 "Left Cerebrum Sub-lobar Gray Matter Lateral Geniculum Body" ,
			 "Left Brainstem Midbrain Gray Matter Medial Geniculum Body" ,
			 "Right Brainstem Midbrain Gray Matter Medial Geniculum Body" ,
			 "Right Cerebrum Sub-lobar Gray Matter Lateral Geniculum Body" ,
			 "Left Cerebrum Sub-lobar Lentiform Nucleus Gray Matter" ,
			 "Right Cerebrum Midbrain Extra-Nuclear White Matter" ,
			 "Left Brainstem Midbrain White Matter" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Anterior Commissure" ,
			 "Inter-Hemispheric White Matter Anterior Commissure" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Anterior Commissure" ,
			 "Left Cerebrum Frontal-Temporal Space Superior Temporal Gyrus" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Corpus Callosum" ,
			 "Inter-Hemispheric White Matter Corpus Callosum" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Corpus Callosum" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear Cerebro-Spinal Fluid" ,
			 "Right Cerebrum Sub-lobar Claustrum White Matter" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral White Matter Corpus Callosum" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral White Matter Corpus Callosum" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 10" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 10" ,
			 "Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter" ,
			 "Right Cerebrum Occipital Lobe Middle Occipital Gyrus Gray Matter" ,
			 "Right Cerebrum Gray Matter" ,
			 "Middle Occipital Gyrus Gray Matter" ,
			 "Inter-Hemispheric Lingual Gyrus" ,
			 "Right Cerebrum Occipital Lobe Lingual Gyrus Gray Matter" ,
			 "Left Cerebrum Limbic Lobe Lingual Gyrus Gray Matter" ,
			 "Middle Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter" ,
			 "Sub-lobar Extra-Nuclear White Matter" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter" ,
			 "Inter-Hemispheric Occipital Lobe Gray Matter" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter" ,
			 "Right Cerebrum Cuneus Gray Matter" ,
			 "Inter-Hemispheric Occipital Lobe Cuneus Gray Matter Brodmann area 18" ,
			 "Inter-Hemispheric Cuneus" ,
			 "Right Cerebrum Occipital Lobe Gray Matter" ,
			 "Inter-Hemispheric Occipital Lobe Cuneus Gray Matter Brodmann area 17" ,
			 "Left Cerebrum Occipital Lobe Lingual Gyrus Gray Matter" ,
			 "Right Cerebrum Middle Occipital Gyrus Gray Matter" ,
			 "Inter-Hemispheric Occipital Lobe Cuneus" ,
			 "Inter-Hemispheric Occipital Lobe Cuneus Gray Matter" ,
			 "Inter-Hemispheric Occipital Lobe Lingual Gyrus Gray Matter" ,
			 "Right Cerebrum Middle Occipital Gyrus" ,
			 "Inter-Hemispheric Occipital Lobe" ,
			 "Left Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter" ,
			 "Right Cerebrum Occipital Lobe Inferior Temporal Gyrus Gray Matter" ,
			 "Inferior Temporal Gyrus Gray Matter" ,
			 "Right Cerebrum Inferior Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Sub-Gyral Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Inferior Temporal Gyrus Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Culmen of Vermis" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 37" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus White Matter" ,
			 "Right Cerebrum Middle Temporal Gyrus" ,
			 "Right Cerebellum Anterior Lobe Culmen Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Temporal Lobe Lingual Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Lingual Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Lingual Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Temporal Lobe Lingual Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Cerebro-Spinal Fluid Caudate Tail" ,
			 "Left Cerebrum Temporal Lobe White Matter" ,
			 "Right Cerebrum Temporal Lobe Extra-Nuclear White Matter" ,
			 "Right Brainstem" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter" ,
			 "Left Brainstem Midbrain Extra-Nuclear White Matter" ,
			 "Right Cerebrum Superior Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Insula Gray Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Ventral Posterior Lateral Nucleus" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Ventral Posterior Medial Nucleus" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Mammillary Body" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Mammillary Body" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Ventral Posterior Medial Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Ventral Posterior Lateral Nucleus" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter" ,
			 "Right Cerebrum Temporal Lobe Insula Gray Matter" ,
			 "Left Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 22" ,
			 "Right Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Temporal Lobe Insula" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Medial Globus Pallidus" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Lateral Globus Pallidus" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Lateral Globus Pallidus" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Putamen" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Putamen" ,
			 "Left Cerebrum Sub-lobar Caudate Cerebro-Spinal Fluid Caudate Head" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Sub-lobar Caudate Cerebro-Spinal Fluid Caudate Head" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 45" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 45" ,
			 "Left Cerebrum Sub-lobar Inferior Frontal Gyrus Gray Matter Brodmann area 47" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 46" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 46" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter" ,
			 "Inter-Hemispheric Frontal Lobe" ,
			 "Right Cerebrum Frontal Lobe Gray Matter" ,
			 "Inter-Hemispheric Sub-lobar Extra-Nuclear White Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Pulvinar" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Pulvinar" ,
			 "Inter-Hemispheric Cerebro-Spinal Fluid Optic Tract" ,
			 "Left Cerebrum Temporal Lobe Middle Occipital Gyrus" ,
			 "Right Cerebrum Temporal Lobe Middle Occipital Gyrus" ,
			 "Right Cerebrum Temporal Lobe Middle Occipital Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Temporal Lobe Middle Occipital Gyrus Gray Matter Brodmann area 37" ,
			 "Left Cerebrum Temporal Lobe Middle Occipital Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Middle Occipital Gyrus White Matter" ,
			 "Left Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Limbic Lobe Parahippocampal Gyrus Gray Matter Brodmann area 18" ,
			 "Inter-Hemispheric Sub-lobar Extra-Nuclear Cerebro-Spinal Fluid Optic Tract" ,
			 "Right Cerebrum Sub-lobar Superior Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Temporal Lobe Insula White Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Medial Dorsal Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Medial Dorsal Nucleus" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear Cerebro-Spinal Fluid Optic Tract" ,
			 "Right Cerebrum Cerebro-Spinal Fluid Optic Tract" ,
			 "Right Cerebrum Sub-lobar Lentiform Nucleus Gray Matter" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear Cerebro-Spinal Fluid Optic Tract" ,
			 "Right Cerebrum Sub-lobar Superior Temporal Gyrus" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Ventral Lateral Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Ventral Lateral Nucleus" ,
			 "Right Cerebrum Thalamus Gray Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Ventral Anterior Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Ventral Anterior Nucleus" ,
			 "Left Cerebrum Frontal-Temporal Space Insula" ,
			 "Left Cerebrum Frontal Lobe Insula" ,
			 "Right Cerebrum Sub-lobar Inferior Frontal Gyrus" ,
			 "Inter-Hemispheric Sub-lobar Extra-Nuclear White Matter Corpus Callosum" ,
			 "Right Cerebrum White Matter Corpus Callosum" ,
			 "Right Cerebrum Sub-lobar Inferior Frontal Gyrus Gray Matter Brodmann area 45" ,
			 "Left Cerebrum Sub-lobar Inferior Frontal Gyrus" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 45" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 45" ,
			 "Right Cerebrum Sub-lobar White Matter Corpus Callosum" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 46" ,
			 "Inter-Hemispheric Frontal Lobe Medial Frontal Gyrus" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 30" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 30" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate White Matter" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 30" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate White Matter" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 30" ,
			 "Left Cerebrum Occipital Lobe Posterior Cingulate White Matter" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate" ,
			 "Right Cerebrum Occipital Lobe Posterior Cingulate Gray Matter Brodmann area 30" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 29" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 29" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 41" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 42" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 42" ,
			 "Right Cerebrum Sub-lobar Extra-Nuclear White Matter Pulvinar" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Ventral Posterior Lateral Nucleus" ,
			 "Left Cerebrum Temporal Lobe Precentral Gyrus" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus" ,
			 "Right Cerebrum Temporal Lobe Precentral Gyrus" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Anterior Nucleus" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus White Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Anterior Nucleus" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus White Matter" ,
			 "Inter-Hemispheric White Matter" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 44" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 44" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 44" ,
			 "Left Cerebrum Sub-lobar Caudate Gray Matter Caudate Body" ,
			 "Right Cerebrum Sub-lobar Caudate Gray Matter Caudate Body" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate White Matter Corpus Callosum" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate White Matter Corpus Callosum" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 46" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 46" ,
			 "Left Cerebrum Middle Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus White Matter" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 23" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 23" ,
			 "Left Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Superior Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Inter-Hemispheric Limbic Lobe Posterior Cingulate" ,
			 "Left Cerebrum Limbic Lobe Extra-Nuclear White Matter Corpus Callosum" ,
			 "Right Cerebrum Limbic Lobe Extra-Nuclear White Matter Corpus Callosum" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral White Matter Corpus Callosum" ,
			 "Inter-Hemispheric Limbic Lobe Extra-Nuclear White Matter Corpus Callosum" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral White Matter Corpus Callosum" ,
			 "Superior Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Transverse Temporal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Transverse Temporal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Transverse Temporal Gyrus Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Temporal Lobe Transverse Temporal Gyrus Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 41" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Sub-lobar Transverse Temporal Gyrus Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Sub-lobar Transverse Temporal Gyrus White Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Lateral Posterior Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Lateral Posterior Nucleus" ,
			 "Right Cerebrum Temporal Lobe Transverse Temporal Gyrus Gray Matter Brodmann area 42" ,
			 "Left Cerebrum Temporal Lobe Transverse Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Transverse Temporal Gyrus Gray Matter Brodmann area 42" ,
			 "Right Cerebrum Temporal Lobe Transverse Temporal Gyrus" ,
			 "Right Cerebrum Temporal Lobe Precentral Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Transverse Temporal Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Sub-lobar Precentral Gyrus Gray Matter Brodmann area 13" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 13" ,
			 "Left Cerebrum Transverse Temporal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Precentral Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Precentral Gyrus Gray Matter Brodmann area 43" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 43" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 43" ,
			 "Right Cerebrum Temporal Lobe Precentral Gyrus Gray Matter Brodmann area 42" ,
			 "Left Cerebrum Temporal Lobe Precentral Gyrus Gray Matter Brodmann area 42" ,
			 "Left Cerebrum Precentral Gyrus" ,
			 "Inter-Hemispheric Sub-lobar Lateral Ventricle Cerebro-Spinal Fluid" ,
			 "Right Cerebrum Precentral Gyrus" ,
			 "Left Cerebrum Frontal Lobe Insula White Matter" ,
			 "Right Cerebrum Frontal Lobe Insula White Matter" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 44" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 44" ,
			 "Left Cerebrum Limbic Lobe Extra-Nuclear" ,
			 "Right Cerebrum Limbic Lobe Extra-Nuclear" ,
			 "Inter-Hemispheric Limbic Lobe Anterior Cingulate" ,
			 "Left Cerebrum Middle Frontal Gyrus" ,
			 "Right Cerebrum Gray Matter Brodmann area 10" ,
			 "Inter-Hemispheric Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 10" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 18" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter" ,
			 "Left Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 23" ,
			 "Right Cerebrum Limbic Lobe Posterior Cingulate Gray Matter Brodmann area 23" ,
			 "Left Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Superior Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Right Cerebrum Occipital Lobe Middle Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Left Cerebrum Occipital Lobe Superior Temporal Gyrus Gray Matter Brodmann area 22" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 41" ,
			 "Right Cerebrum Temporal Lobe Insula White Matter" ,
			 "Left Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 41" ,
			 "Right Cerebrum Temporal Lobe Insula Gray Matter Brodmann area 41" ,
			 "Left Cerebrum Temporal Lobe Postcentral Gyrus" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Insula White Matter" ,
			 "Left Cerebrum Sub-lobar Extra-Nuclear White Matter Pulvinar" ,
			 "Right Cerebrum Parietal Lobe Insula White Matter" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Temporal Lobe Postcentral Gyrus" ,
			 "Right Cerebrum Parietal Lobe Superior Temporal Gyrus" ,
			 "Right Cerebrum Sub-lobar Insula Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus" ,
			 "Left Cerebrum Parietal Lobe Superior Temporal Gyrus" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus White Matter" ,
			 "Left Cerebrum Sub-lobar Insula Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus White Matter" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Lateral Dorsal Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Lateral Dorsal Nucleus" ,
			 "Left Cerebrum Postcentral Gyrus" ,
			 "Left Cerebrum Sub-lobar Thalamus Gray Matter Midline Nucleus" ,
			 "Right Cerebrum Sub-lobar Thalamus Gray Matter Midline Nucleus" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 43" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 43" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter" ,
			 "Left Cerebrum Parietal Lobe Sub-Gyral White Matter" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 43" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral White Matter" ,
			 "Left Cerebrum Parietal Lobe" ,
			 "Left Cerebrum Parietal Lobe Precentral Gyrus White Matter" ,
			 "Left Cerebrum Parietal Lobe Extra-Nuclear White Matter" ,
			 "Right Cerebrum Parietal Lobe Precentral Gyrus White Matter" ,
			 "Left Cerebrum Parietal Lobe Precentral Gyrus" ,
			 "Left Cerebrum Parietal Lobe Precentral Gyrus Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Parietal Lobe Precentral Gyrus Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Parietal Lobe Precentral Gyrus" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 4" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Inferior Frontal Gyrus" ,
			 "Middle Frontal Gyrus" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Superior Frontal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Temporal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Temporal Lobe Middle Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Occipital Lobe Precuneus White Matter" ,
			 "Right Cerebrum Occipital Lobe Precuneus White Matter" ,
			 "Left Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Occipital Lobe Precuneus" ,
			 "Left Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Occipital Lobe Precuneus" ,
			 "Left Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 23" ,
			 "Right Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 23" ,
			 "Left Cerebrum Sub-lobar Posterior Cingulate White Matter" ,
			 "Right Cerebrum Sub-lobar Posterior Cingulate White Matter" ,
			 "Left Cerebrum Frontal Lobe Postcentral Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Postcentral Gyrus White Matter" ,
			 "Left Cerebrum Frontal Lobe Postcentral Gyrus Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Postcentral Gyrus Gray Matter Brodmann area 4" ,
			 "Precentral Gyrus" ,
			 "Left Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 33" ,
			 "Right Cerebrum Limbic Lobe Anterior Cingulate Gray Matter Brodmann area 33" ,
			 "Inter-Hemispheric Anterior Cingulate" ,
			 "Left Cerebrum Frontal Lobe Anterior Cingulate Gray Matter Brodmann area 9" ,
			 "Cuneus" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 19" ,
			 "Superior Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Superior Occipital Gyrus" ,
			 "Right Cerebrum Occipital Lobe Superior Occipital Gyrus" ,
			 "Left Cerebrum Occipital Lobe Superior Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Occipital Lobe Superior Occipital Gyrus Gray Matter Brodmann area 19" ,
			 "Left Cerebrum Occipital Lobe Superior Occipital Gyrus White Matter" ,
			 "Right Cerebrum Occipital Lobe Superior Occipital Gyrus White Matter" ,
			 "Left Cerebrum Temporal Lobe Superior Occipital Gyrus" ,
			 "Right Cerebrum Temporal Lobe Superior Occipital Gyrus" ,
			 "Left Cerebrum Temporal Lobe Cuneus White Matter" ,
			 "Right Cerebrum Temporal Lobe Cuneus White Matter" ,
			 "Left Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 18" ,
			 "Right Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Precuneus White Matter" ,
			 "Left Cerebrum Parietal Lobe Precuneus" ,
			 "Right Cerebrum Parietal Lobe Precuneus" ,
			 "Right Cerebrum Temporal Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Parietal Lobe Precuneus White Matter" ,
			 "Frontal Lobe Middle Temporal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Precuneus White Matter" ,
			 "Left Cerebrum Temporal Lobe Precuneus White Matter" ,
			 "Left Cerebrum Temporal Lobe Supramarginal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Supramarginal Gyrus Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Temporal Lobe Supramarginal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Supramarginal Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Supramarginal Gyrus Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Temporal Lobe Supramarginal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Inferior Parietal Lobule White Matter" ,
			 "Right Cerebrum Parietal Lobe Extra-Nuclear White Matter" ,
			 "Right Cerebrum Temporal Lobe Inferior Parietal Lobule White Matter" ,
			 "Left Cerebrum Temporal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule White Matter" ,
			 "Right Cerebrum Parietal Lobe Inferior Parietal Lobule White Matter" ,
			 "Right Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Supramarginal Gyrus" ,
			 "Right Cerebrum Parietal Lobe Supramarginal Gyrus" ,
			 "Left Cerebrum Temporal Lobe Inferior Parietal Lobule" ,
			 "Right Cerebrum Temporal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Temporal Lobe Inferior Parietal Lobule" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule" ,
			 "Inter-Hemispheric Limbic Lobe" ,
			 "Right Cerebrum Parietal Lobe Inferior Parietal Lobule" ,
			 "Left Cerebrum Limbic Lobe White Matter" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 2" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 2" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 1" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 1" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 3" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Frontal Lobe Postcentral Gyrus Gray Matter Brodmann area 3" ,
			 "Right Cerebrum Frontal Lobe Postcentral Gyrus Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Inferior Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Inter-Hemispheric Superior Frontal Gyrus" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Temporal Lobe Superior Occipital Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Superior Occipital Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Occipital Lobe Superior Occipital Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Occipital Lobe Superior Occipital Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Limbic Lobe Precuneus" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus" ,
			 "Right Cerebrum Limbic Lobe Precuneus" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Sub-Gyral Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Limbic Lobe Precuneus White Matter" ,
			 "Left Cerebrum Limbic Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus White Matter" ,
			 "Right Cerebrum Limbic Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Limbic Lobe Precuneus White Matter" ,
			 "Left Cerebrum Occipital Lobe Superior Temporal Gyrus" ,
			 "Right Cerebrum Occipital Lobe Superior Temporal Gyrus" ,
			 "Left Cerebrum Parietal Lobe Supramarginal Gyrus Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Supramarginal Gyrus Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Supramarginal Gyrus White Matter" ,
			 "Right Cerebrum Parietal Lobe Supramarginal Gyrus White Matter" ,
			 "Supramarginal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 31" ,
			 "Inferior Parietal Lobule" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 23" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 23" ,
			 "Left Cerebrum Frontal Lobe Inferior Parietal Lobule White Matter" ,
			 "Right Cerebrum Frontal Lobe Inferior Parietal Lobule White Matter" ,
			 "Left Cerebrum Parietal Lobe Precentral Gyrus Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 3" ,
			 "Right Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 24" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 24" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Limbic Lobe Medial Frontal Gyrus Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Limbic Lobe Medial Frontal Gyrus Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Limbic Lobe Medial Frontal Gyrus" ,
			 "Right Cerebrum Limbic Lobe Medial Frontal Gyrus" ,
			 "Right Cerebrum Cuneus" ,
			 "Left Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Occipital Lobe Cuneus Gray Matter Brodmann area 7" ,
			 "Angular Gyrus" ,
			 "Left Cerebrum Occipital Lobe Angular Gyrus" ,
			 "Right Cerebrum Occipital Lobe Angular Gyrus" ,
			 "Left Cerebrum Temporal Lobe Angular Gyrus" ,
			 "Left Cerebrum Temporal Lobe Angular Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Angular Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Temporal Lobe Angular Gyrus" ,
			 "Left Cerebrum Temporal Lobe Angular Gyrus White Matter" ,
			 "Right Cerebrum Temporal Lobe Angular Gyrus White Matter" ,
			 "Left Cerebrum Parietal Lobe Cuneus White Matter" ,
			 "Right Cerebrum Parietal Lobe Cuneus White Matter" ,
			 "Left Cerebrum Parietal Lobe Angular Gyrus White Matter" ,
			 "Right Cerebrum Parietal Lobe Angular Gyrus White Matter" ,
			 "Left Cerebrum Parietal Lobe Angular Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Angular Gyrus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Occipital Lobe Precuneus Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 7" ,
			 "Parietal Lobe" ,
			 "Left Cerebrum Parietal Lobe Supramarginal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Parietal Lobe Supramarginal Gyrus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Precuneus" ,
			 "Right Cerebrum Parietal Lobe" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 2" ,
			 "Left Cerebrum Frontal Lobe Postcentral Gyrus" ,
			 "Right Cerebrum Frontal Lobe Postcentral Gyrus" ,
			 "Left Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Limbic Lobe Cingulate Gyrus Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 9" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Parietal Lobe Cuneus" ,
			 "Left Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 19" ,
			 "Right Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 19" ,
			 "Inter-Hemispheric Precuneus" ,
			 "Right Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Parietal Lobe Precuneus Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Parietal Lobe Angular Gyrus Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Angular Gyrus Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Cingulate Gyrus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Cingulate Gyrus" ,
			 "Right Cerebrum Parietal Lobe Cingulate Gyrus" ,
			 "Right Cerebrum Parietal Lobe Cingulate Gyrus Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Frontal Lobe Cingulate Gyrus White Matter" ,
			 "Right Cerebrum Frontal Lobe Cingulate Gyrus White Matter" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 4" ,
			 "Left Cerebrum Frontal Lobe Precentral Gyrus Gray Matter Brodmann area 9" ,
			 "Left Cerebrum Frontal Lobe Cingulate Gyrus" ,
			 "Left Cerebrum Frontal Lobe Cingulate Gyrus Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Frontal Lobe Cingulate Gyrus" ,
			 "Right Cerebrum Frontal Lobe Cingulate Gyrus Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Frontal Lobe Cingulate Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Cingulate Gyrus Gray Matter Brodmann area 6" ,
			 "Precuneus" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 39" ,
			 "Right Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 39" ,
			 "Left Cerebrum Frontal Lobe Precuneus Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 2" ,
			 "Right Cerebrum Parietal Lobe Precentral Gyrus Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 24" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 24" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Right Cerebrum Frontal Lobe Middle Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 8" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 8" ,
			 "Left Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Limbic Lobe Sub-Gyral Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 32" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 32" ,
			 "Left Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 8" ,
			 "Left Cerebrum Parietal Lobe Superior Parietal Lobule" ,
			 "Right Cerebrum Parietal Lobe Superior Parietal Lobule" ,
			 "Left Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 7" ,
			 "Left Cerebrum Parietal Lobe Superior Parietal Lobule White Matter" ,
			 "Right Cerebrum Parietal Lobe Superior Parietal Lobule White Matter" ,
			 "Left Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 7" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule" ,
			 "Inter-Hemispheric Paracentral Lobule" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 31" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule White Matter" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule White Matter" ,
			 "Left Cerebrum Limbic Lobe Paracentral Lobule Gray Matter Brodmann area 31" ,
			 "Left Cerebrum Limbic Lobe Paracentral Lobule White Matter" ,
			 "Right Cerebrum Limbic Lobe Paracentral Lobule White Matter" ,
			 "Left Cerebrum Limbic Lobe Paracentral Lobule" ,
			 "Right Cerebrum Limbic Lobe Paracentral Lobule" ,
			 "Inter-Hemispheric Cingulate Gyrus" ,
			 "Inter-Hemispheric Medial Frontal Gyrus" ,
			 "Superior Parietal Lobule" ,
			 "Left Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Right Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Parietal Lobe Paracentral Lobule White Matter" ,
			 "Left Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 5" ,
			 "Left Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 5" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 5" ,
			 "Right Cerebrum Frontal Lobe Precuneus" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 5" ,
			 "Left Cerebrum Parietal Lobe Paracentral Lobule" ,
			 "Right Cerebrum Parietal Lobe Paracentral Lobule" ,
			 "Right Cerebrum Parietal Lobe Paracentral Lobule White Matter" ,
			 "Right Cerebrum Frontal Lobe Precuneus White Matter" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Frontal Lobe Superior Frontal Gyrus Gray Matter Brodmann area 6" ,
			 "Right Cerebrum Superior Parietal Lobule" ,
			 "Left Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Sub-Gyral Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Frontal Lobe Inferior Parietal Lobule Gray Matter Brodmann area 40" ,
			 "Left Cerebrum Frontal Lobe Precuneus Gray Matter Brodmann area 5" ,
			 "Left Cerebrum Frontal Lobe Precuneus White Matter" ,
			 "Left Cerebrum Frontal Lobe Precuneus" ,
			 "Right Cerebrum Frontal Lobe Precuneus Gray Matter Brodmann area 5" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 7" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 3" ,
			 "Left Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Paracentral Lobule Gray Matter Brodmann area 3" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 3" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Sub-Gyral Gray Matter Brodmann area 6" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 5" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 5" ,
			 "Left Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 5" ,
			 "Right Cerebrum Parietal Lobe Superior Parietal Lobule Gray Matter Brodmann area 5" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Frontal Lobe Medial Frontal Gyrus Gray Matter Brodmann area 4" ,
			 "Left Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 7" ,
			 "Right Cerebrum Parietal Lobe Postcentral Gyrus Gray Matter Brodmann area 7" ,
			 "Inter-Hemispheric Postcentral Gyrus" ,
			 "Left Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 4" ,
			 "Right Cerebrum Parietal Lobe Paracentral Lobule Gray Matter Brodmann area 4" ,
    		};
	
}
