function mtypes = cpca_xyzt_types()
% ------------------------------------
% --- original analyze 7.5 data type codes
% ---
% --- codes > 128 are nifti codes
% --- analyze 7.5 has no binary code


  fields = {'code', 'type', 'descr'};

 measurement = [ ...
  [ 0 				{'?'}			{'Measurement invalid'}]; ...
  [ 1 				{'M'}                   {'Meters'}]; ...
  [ 2 				{'mm'}                  {'Millimeters'} ]; ...
  [ 3 				{'um'}			{'micrometers'} ]; ...
  [ 8 				{'seconds'}		{'seconds'} ]; ...
  [16 				{'ms'}   		{'milliSeconds'} ]; ...
  [24 				{'um'}			{'microseconds'} ]; ...
  [32				{'Hz'}		 	{'hertz'} ]; ...
  [40				{'ppm'}		 	{'parts per million'} ]; ...
  [48 				{'rad'}			{'radians'} ]];

  mtypes = cell2struct( measurement, fields, 2 );

