function s = new_image_struct()

  s = struct( 'header', [], ...
              'image', [], ...
              'vol', [], ...
              'niiSingle', 0, ...
              'file', '', ...
              'ind', [], ...
              'x', 0, ...
              'y', 0, ...
              'tal_index', [], ...
              'MNI', [] ...
 );


