function h = new_nifti_header()

h = struct( ...
  'sizeof_hdr', 348, ...
  'data_type', '', ...
  'db_name', '', ...
  'extents', 0, ...
  'session_error', 0, ...
  'regular', 'r', ...
  'dim_info', '', ...
  'dim', [3 0 0 0  1 1 1 1 1], ...
  'intent_p1', 0, ...
  'intent_p2', 0, ...
  'intent_p3', 0, ...
  'intent_code', 0, ...
  'datatype', 4, ...
  'bitpix', 16, ...
  'slice_start', 0, ...
  'pixdim', [0 1 1 1], ...
  'vox_offset', 0 , ...
  'scl_slope', 1, ...
  'scl_inter', 0, ...
  'slice_end', 0, ...
  'slice_code', 0, ...
  'xyzt_units', 10, ...
  'cal_max', 0, ...
  'cal_min', 0, ...
  'slice_duration', 0, ...
  'toffset', 0, ...
  'glmax', 0, ...
  'glmin', 0, ...
  'description', 'NIFTI-1 Image', ...
  'aux_file', '', ...
  'qform_code', 0, ...
  'sform_code', 0, ...
  'quatern_b', 0, ...
  'quatern_c', 0, ...
  'quatern_d', 0, ...
  'qoffset_x', 0, ...
  'qoffset_y', 0, ...
  'qoffset_z', 0, ...
  'srow_x', [1 0 0 0], ...
  'srow_y', [0 1 0 0], ...
  'srow_z', [0 0 1 0], ...
  'intent_name', '', ...
  'magic', 'ni1' );

